export const TOKENS = {
  
  IUserRepository: Symbol.for("IUserRepository"),
  IOwnerRepository: Symbol.for("IOwnerRepository"),
  IAdminRepository: Symbol.for("IAdminRepository"),
  IBaseRepository: Symbol.for("IBaseRepository"),
  IPropertyRepository: Symbol.for("IPropertyRepository"),
  IBookingRepository: Symbol.for("IBookingRepository"),
  IWalletRepository:Symbol.for("IWalletRepository"),
  IReviewRepository:Symbol.for("IReviewRepository"),
  INotificationRepository:Symbol.for("INotificationRepository"),
  ISubscriptionPlanRepository:Symbol.for("ISubscriptionPlanRepository"),
  ISubscriptionRepository:Symbol.for("ISubscriptionRepository"),
  
  IUserService: Symbol.for("IUserService"),
  IOwnerService: Symbol.for("IOwnerService"),
  IAdminService: Symbol.for("IAdminService"),
  IPropertyService: Symbol.for("IPropertyService"),
  IBookingService:Symbol.for("IBookingService"),
  IReviewService:Symbol.for("IReviewService"),
  INotificationService:Symbol.for("INotificationService"),
  IAdminSubscriptionService:Symbol.for("IAdminSubscriptionService"),
  ISubscriptionService:Symbol.for("ISubscriptionService"),

  IUserController: Symbol.for("IUserController"),
  IOwnerController: Symbol.for("IOwnerController"),
  IAdminController: Symbol.for("IAdminController"),
  IPropertyController: Symbol.for("IPropertyController"),
  IBookingController: Symbol.for("IBookingController"),
  IReviewController: Symbol.for("IReviewController"),
  INotificationController: Symbol.for("INotificationController"),
  IAdminSubscriptionController: Symbol.for("IAdminSubscriptionController"),
  ISubscriptionController: Symbol.for("ISubscriptionController"),

  IOTPService: Symbol.for("IOTPService"),
  ILogger: Symbol.for("ILogger"),
};